LANGUAGES = {
    "en": "English",
    "es": "Español",
    "ca": "Català",
}

def get_translation(lang_code, key, **kwargs):
    """Retrieve a translation with graceful fallback."""
    translations = TRANSLATIONS.get(lang_code, TRANSLATIONS.get("en", {}))
    text = translations.get(key, f"MISSING_TRANSLATION[{key}]")
    try:
        return text.format(**kwargs)
    except Exception:
        return text

TRANSLATIONS = {
    "en": {
        "gym_churn_predictor": "GYM CHURN PREDICTOR",
        "login_register": "Login or Register",
        "login_to_your_account": "Login to your Account",
        "username": "Username",
        "password": "Password",
        "login": "Login",
        "invalid_username_or_password": "Invalid Username or Password",
        "create_a_new_account": "Create a New Account",
        "new_username": "New Username",
        "new_password": "New Password",
        "confirm_password": "Confirm Password",
        "passwords_do_not_match": "Passwords do not match.",
        "username_already_exists": "Username already exists. Please choose a different one.",
        "account_created_successfully": "Account created successfully! Please login.",
        "register": "Register",
        "ai_powered_insights": "AI-powered insights for member retention",
        "gym_churn_predictor_dashboard": "Gym Churn Predictor Dashboard",
        "welcome": "Welcome, {username}!",
        "data_overview": "Data Overview",
        "total_users": "Total Users",
        "total_visits": "Total Visits",
        "churned_users": "Churned Users",
        "active_users": "Active Users",
        "users_at_risk": "Users at Risk",
        "churn_rate": "Churn Rate",
        "features_used_to_predict_churn": "Features used to Predict Churn",
        "features_created": "Features created: {shape}",
        "trained_model_loaded_successfully": "Trained AI model loaded successfully!",
        "no_trained_model_found": "No trained model found. Training a new model now...",
        "new_model_trained_and_saved": "New model trained and saved!",
        "feature_importance": "Importance of each feature to predict churn",
        "summary_statistics": "Summary Statistics",
        "churned_vs_active_users_comparison": "Churned vs Active Users Comparison",
        "at_risk_active_users": "At-Risk Active Users",
        "top_10_at_risk_users": "Top 10 At-Risk Users:",
        "high_risk_users_message": "Our AI predictor has detected {n} users at high churn risk.",
        "back_to_first_10": "Back to First 10",
        "load_next_10_at_risk_users": "Load Next 10 At-Risk Users",
        "risk_level_high": "High",
        "risk_level_medium": "Medium",
        "risk_level_low": "Low",
        "password_requirements": "Password must be at least 9 characters long and contain at least one capital letter, one number, and one letter",
        "how_the_ai_model_works": "How the AI Model Works",
        "model_explanation_title": "Understanding Your Gym Member Retention AI",
        "model_explanation_text": "Our AI model analyzes your gym members' behavior patterns to predict who might stop coming to the gym. Here's how it works in simple terms:",
        "model_step_1": "📊 Data Collection: We look at member information like registration dates, membership types, and visit patterns.",
        "model_step_2": "🔍 Pattern Recognition: The AI learns from past data to identify what behaviors typically lead to members leaving (churning).",
        "model_step_3": "🎯 Risk Prediction: For each active member, the AI calculates a risk score from Low to High based on their recent activity.",
        "model_step_4": "📈 Actionable Insights: You get a prioritized list of members to focus your retention efforts on, saving time and money.",
        "model_why_important": "This helps gym owners like you proactively reach out to members before they leave, improving retention rates and business success.",
        "how_it_works_section": "How It Works:",
        "why_this_matters_section": "Why This Matters:",
        "data_collection_title": "Data Collection",
        "pattern_recognition_title": "Pattern Recognition",
        "risk_prediction_title": "Risk Prediction",
        "actionable_insights_title": "Actionable Insights",
        "model_documentation_loading_title": "AI Model Documentation",
        "loading_message": "Loading...",
        "loading_users_message": "Loading users..."
    },
    "es": {
        "gym_churn_predictor": "PREDICTOR DE BAJA DE GIMNASIO",
        "login_register": "Iniciar sesión o Registrarse",
        "login_to_your_account": "Iniciar sesión en tu cuenta",
        "username": "Nombre de usuario",
        "password": "Contraseña",
        "login": "Iniciar sesión",
        "invalid_username_or_password": "Nombre de usuario o contraseña inválidos",
        "create_a_new_account": "Crear una nueva cuenta",
        "new_username": "Nuevo nombre de usuario",
        "new_password": "Nueva contraseña",
        "confirm_password": "Confirmar contraseña",
        "passwords_do_not_match": "Las contraseñas no coinciden.",
        "username_already_exists": "El nombre de usuario ya existe. Por favor, elige otro.",
        "account_created_successfully": "¡Cuenta creada exitosamente! Por favor, inicia sesión.",
        "register": "Registrarse",
        "ai_powered_insights": "Análisis impulsado por IA para la retención de miembros",
        "gym_churn_predictor_dashboard": "Panel de Predicción de Bajas de Gimnasio",
        "welcome": "¡Bienvenido, {username}!",
        "data_overview": "Resumen de Datos",
        "total_users": "Usuarios Totales",
        "total_visits": "Visitas Totales",
        "churned_users": "Usuarios Dados de Baja",
        "active_users": "Usuarios Activos",
        "users_at_risk": "Usuarios en Riesgo",
        "churn_rate": "Tasa de Baja",
        "features_used_to_predict_churn": "Características utilizadas para predecir la baja",
        "features_created": "Características creadas: {shape}",
        "trained_model_loaded_successfully": "¡Modelo de IA entrenado cargado exitosamente!",
        "no_trained_model_found": "No se encontró ningún modelo entrenado. Entrenando uno nuevo ahora...",
        "new_model_trained_and_saved": "¡Nuevo modelo entrenado y guardado!",
        "feature_importance": "Importancia de cada característica para predecir el abandono",
        "summary_statistics": "Estadísticas Resumidas",
        "churned_vs_active_users_comparison": "Comparación de Usuarios Dados de Baja vs Activos",
        "at_risk_active_users": "Usuarios Activos en Riesgo",
        "top_10_at_risk_users": "Top 10 Usuarios en Riesgo:",
        "high_risk_users_message": "Nuestro predictor de IA ha detectado {n} usuarios con alto riesgo de baja.",
        "back_to_first_10": "Volver a los primeros 10",
        "load_next_10_at_risk_users": "Cargar próximos 10 usuarios en riesgo",
        "risk_level_high": "Alto",
        "risk_level_medium": "Medio",
        "risk_level_low": "Bajo",
        "password_requirements": "La contraseña debe tener al menos 9 caracteres y contener al menos una letra mayúscula, un número y una letra",
        "how_the_ai_model_works": "Cómo Funciona el Modelo de IA",
        "model_explanation_title": "Entendiendo tu IA de Retención de Miembros del Gimnasio",
        "model_explanation_text": "Nuestro modelo de IA analiza los patrones de comportamiento de los miembros del gimnasio para predecir quién podría dejar de venir. Aquí te explicamos cómo funciona de manera sencilla:",
        "model_step_1": "📊 Recopilación de Datos: Observamos información de los miembros como fechas de registro, tipos de membresía y patrones de visitas.",
        "model_step_2": "🔍 Reconocimiento de Patrones: La IA aprende de datos pasados para identificar qué comportamientos suelen llevar a que los miembros se vayan (abandono).",
        "model_step_3": "🎯 Predicción de Riesgo: Para cada miembro activo, la IA calcula una puntuación de riesgo de Bajo a Alto basada en su actividad reciente.",
        "model_step_4": "📈 Información Accionable: Obtienes una lista priorizada de miembros en los que enfocar tus esfuerzos de retención, ahorrando tiempo y dinero.",
        "model_why_important": "Esto ayuda a propietarios de gimnasios como tú a contactar proactivamente con los miembros antes de que se vayan, mejorando las tasas de retención y el éxito del negocio.",
        "how_it_works_section": "Cómo Funciona:",
        "why_this_matters_section": "Por Qué Importa:",
        "data_collection_title": "Recopilación de Datos",
        "pattern_recognition_title": "Reconocimiento de Patrones",
        "risk_prediction_title": "Predicción de Riesgo",
        "actionable_insights_title": "Información Accionable",
        "model_documentation_loading_title": "Documentación del Modelo de IA",
        "loading_message": "Cargando...",
        "loading_users_message": "Cargando usuarios..."
    },
    "ca": {
        "gym_churn_predictor": "PREDICTOR DE BAIMES DE GIMNÀS",
        "login_register": "Iniciar sessió o Registrar-se",
        "login_to_your_account": "Inicia sessió al teu compte",
        "username": "Nom d'usuari",
        "password": "Contrasenya",
        "login": "Iniciar sessió",
        "invalid_username_or_password": "Nom d'usuari o contrasenya invàlids",
        "create_a_new_account": "Crear un nou compte",
        "new_username": "Nou nom d'usuari",
        "new_password": "Nova contrasenya",
        "confirm_password": "Confirmar contrasenya",
        "passwords_do_not_match": "Les contrasenyes no coincideixen.",
        "username_already_exists": "El nom d'usuari ja existeix. Si us plau, tria un altre.",
        "account_created_successfully": "Compte creat correctament! Si us plau, inicia sessió.",
        "register": "Registrar-se",
        "ai_powered_insights": "Anàlisi impulsada per IA per a la retenció de membres",
        "gym_churn_predictor_dashboard": "Panell de Predicció de Baixes de Gimnàs",
        "welcome": "Benvingut, {username}!",
        "data_overview": "Resum de Dades",
        "total_users": "Usuaris Totals",
        "total_visits": "Visites Totals",
        "churned_users": "Usuaris Donats de Baixa",
        "active_users": "Usuaris Actius",
        "users_at_risk": "Usuaris en Risc",
        "churn_rate": "Taxa de Baixa",
        "features_used_to_predict_churn": "Característiques utilitzades per predir la baixa",
        "features_created": "Característiques creades: {shape}",
        "trained_model_loaded_successfully": "Model d'IA entrenat carregat correctament!",
        "no_trained_model_found": "No s'ha trobat cap model entrenat. Entrenant-ne un de nou ara...",
        "new_model_trained_and_saved": "Nou model entrenat i guardat!",
        "feature_importance": "Importància de cada característica per predir l'abandonament",
        "summary_statistics": "Estadístiques Resumides",
        "churned_vs_active_users_comparison": "Comparació d'Usuaris Donats de Baixa vs Actius",
        "at_risk_active_users": "Usuaris Actius en Risc",
        "top_10_at_risk_users": "Top 10 Usuaris en Risc:",
        "high_risk_users_message": "El nostre predictor d'IA ha detectat {n} usuaris amb alt risc de baixa.",
        "back_to_first_10": "Tornar als primers 10",
        "load_next_10_at_risk_users": "Carregar propers 10 usuaris en risc",
        "risk_level_high": "Alt",
        "risk_level_medium": "Mitjà",
        "risk_level_low": "Baix",
        "password_requirements": "La contrasenya ha de tenir almenys 9 caràcters i contenir almenys una lletra majúscula, un número i una lletra",
        "how_the_ai_model_works": "Com Funciona el Model d'IA",
        "model_explanation_title": "Entenent la teva IA de Retenció de Membres del Gimnàs",
        "model_explanation_text": "El nostre model d'IA analitza els patrons de comportament dels membres del gimnàs per predir qui podria deixar de venir. Aquí t'expliquem com funciona de manera senzilla:",
        "model_step_1": "📊 Recopilació de Dades: Observem informació dels membres com dates de registre, tipus de membresía i patrons de visites.",
        "model_step_2": "🔍 Reconeixement de Patrons: La IA aprèn de dades passades per identificar quins comportaments solen portar a que els membres se'n vagin (abandó).",
        "model_step_3": "🎯 Predicció de Risc: Per cada membre actiu, la IA calcula una puntuació de risc de Baix a Alt basada en la seva activitat recent.",
        "model_step_4": "📈 Informació Accionable: Obtens una llista prioritzada de membres en els que enfocar els teus esforços de retenció, estalviant temps i diners.",
        "model_why_important": "Això ajuda a propietaris de gimnàs com tu a contactar proactivament amb els membres abans que se'n vagin, millorant les taxes de retenció i l'èxit del negoci.",
        "how_it_works_section": "Com Funciona:",
        "why_this_matters_section": "Per Què Importa:",
        "data_collection_title": "Recopilació de Dades",
        "pattern_recognition_title": "Reconeixement de Patrons",
        "risk_prediction_title": "Predicció de Risc",
        "actionable_insights_title": "Informació Accionable",
        "model_documentation_loading_title": "Documentació del Model d'IA",
        "loading_message": "Carregant...",
        "loading_users_message": "Carregant usuaris..."
    }
}